# --- GIAI ĐOẠN 1: BUILD ---
FROM node:22-alpine as build-stage

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Lệnh build của Vite (tạo ra thư mục dist)
RUN npm run build

# --- GIAI ĐOẠN 2: RUN VỚI NGINX ---
FROM nginx:alpine as production-stage

# Copy file đã build từ giai đoạn 1 sang thư mục của Nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copy file cấu hình nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]